/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-nTSDR_Local
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_NTSDR_LOCAL_API_H
#define INCLUDED_NTSDR_LOCAL_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_nTSDR_Local_EXPORTS
#define NTSDR_LOCAL_API __GR_ATTR_EXPORT
#else
#define NTSDR_LOCAL_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NTSDR_LOCAL_API_H */
